In [3]:
import re
import pandas as pd

In [4]:
f = open('friends_group.txt', 'r',encoding='utf-8')

In [5]:
data = f.read()

In [12]:
print(type(data))

<class 'str'>

In [26]:
pattern = r'\d{1,2}/\d{1,2}/\d{2,4},\s\d{1,2}:\d{2}\s-\s'

In [13]:
messages = re.split(pattern, data)[1:]
messages

[]

In [14]:
dates = re.findall(pattern, data)
dates

[]

In [16]:
df = pd.DataFrame({'user_message':messages, 'message_date': dates})
#Convert Message_Date Type
df['message_date'] = pd.to_datetime(df['message_date'], format='%d/m/%Y, %H:%M -')

df.rename(columns={'message_date':'date'}, inplace=True)

df.head()

Empty DataFrame
Columns: [user_message, date]
Index: []

In [17]:
df.shape

(0, 2)

In [19]:
# seperate users and messgaes
users = []
messages = []
for message in df['user_message']:
    entry = re.split('([\w\W]+?):\s', message)
    if entry[1:]: #user name
        users.append(entry[1])
        messages.append(entry[2])
    else:
        users.append('group_notification')
        messages.append(entry[0])

    df['user'] = users
    df['messages'] = messages
    df.drop(columns=['user_message'], inplace=True)

    df.head()

<>:5: SyntaxWarning: invalid escape sequence '\w'
<>:5: SyntaxWarning: invalid escape sequence '\w'
C:\Users\Nishi\AppData\Local\Temp\ipykernel_21512\2129325860.py:5: SyntaxWarning: invalid escape sequence '\w'
  entry = re.split('([\w\W]+?):\s', message)

In [20]:
df['date'].dt.year

Series([], Name: date, dtype: int32)

In [21]:
df['year'] = df['date'].dt.year

In [22]:
df.head()

Empty DataFrame
Columns: [user_message, date, year]
Index: []

In [23]:
df['month'] = df['date'].dt.month_name()

In [24]:
df['date'].dt.day

Series([], Name: date, dtype: int32)

In [ ]:
df['day'] = df['date'].dt.day

In [ ]:
df['hour'] = df['date'].dt.hour

In [ ]:
df['minute'] = df['date'].dt.minute

In [25]:
df.head()

Empty DataFrame
Columns: [user_message, date, year, month]
Index: []